aiServingNamespace: ai-serving
devspacesGlobalConfig:
  enabled: true
guardrails:
  enabled: false
  endpoint: "http://pca-guardrails:8034/guardrailed"
devspaces:
  - namespace: dev-user1-devspaces
    name: code-workspace-1
    user: dev-user1
  - namespace: dev-user2-devspaces
    name: code-workspace-2
    user: dev-user2
  - namespace: dev-user3-devspaces
    name: code-workspace-3
    user: dev-user3
