aiServingNamespace: ai-serving
devspaces:
  - namespace: dev-user1-devspaces
    name: code-workspace-1
  - namespace: dev-user2-devspaces
    name: code-workspace-2
  - namespace: dev-user3-devspaces
    name: code-workspace-3
