namespace: ai-serving
clusterConfig:
  enabled: true
devspaces:
  enabled: true
  instances:
    - namespace: dev-user1-devspaces
      name: code-workspace-1
      user: dev-user1
      password: ""
    - namespace: dev-user2-devspaces
      name: code-workspace-2
      user: dev-user2
      password: ""
    - namespace: dev-user3-devspaces
      name: code-workspace-3
      user: dev-user3
      password: ""
hfToken:
  raw: "__overridden_at_deploy_time__"
guardrails:
  enabled: false
auth:
  htpasswd:
    enabled: false
    providerName: "pca-htpasswd"
