namespace: ai-serving
clusterConfig:
  enabled: true
devspaces:
  enabled: true
  namespaceSuffix: "-devspaces"
hfToken:
  raw: "__overridden_at_deploy_time__"

users:
  - username: dev-user1
    password: ""
  - username: dev-user2
    password: ""
  - username: dev-user3
    password: ""

auth:
  htpasswd:
    enabled: false
    providerName: "pca-htpasswd"
