# Namespaces for the AI platform and developer workspaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-serving
  labels:
    app.kubernetes.io/part-of: private-code-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev1-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev2-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev3-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    argocd.argoproj.io/sync-wave: "0"
