#!/usr/bin/env python3
"""Sync guardrails secret regex patterns from vendored gitleaks rules.

Reads scripts/vendor/gitleaks-v8.24.2.toml (pinned to .pre-commit-config.yaml),
merges charts/pca-ai-serving/charts/pca-guardrails/files/secret-patterns-overrides.yaml,
and writes charts/pca-ai-serving/charts/pca-guardrails/files/secret-patterns.yaml.

Usage:
  python scripts/sync-guardrails-secret-patterns.py
  python scripts/sync-guardrails-secret-patterns.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GITLEAKS_VENDOR = REPO_ROOT / "scripts" / "vendor" / "gitleaks-v8.24.2.toml"
GITLEAKS_VERSION = "v8.24.2"
OVERRIDES_PATH = (
    REPO_ROOT
    / "charts"
    / "pca-ai-serving"
    / "charts"
    / "pca-guardrails"
    / "files"
    / "secret-patterns-overrides.yaml"
)
OUTPUT_PATH = (
    REPO_ROOT
    / "charts"
    / "pca-ai-serving"
    / "charts"
    / "pca-guardrails"
    / "files"
    / "secret-patterns.yaml"
)


def _load_yaml_simple(path: Path) -> dict:
    """Minimal YAML loader for overrides (lists only; no PyYAML dependency)."""
    data: dict[str, list[str]] = {"add": [], "remove": []}
    current_key: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.endswith(":") and not line.startswith("-"):
            key = line[:-1].strip()
            if key in ("add", "remove"):
                current_key = key
            continue
        if line.startswith("- ") and current_key:
            value = line[2:].strip()
            if value.startswith("'") and value.endswith("'"):
                value = value[1:-1]
            elif value.startswith('"') and value.endswith('"'):
                value = value[1:-1]
            data[current_key].append(value)
    return data


def _format_yaml(metadata: dict, patterns: list[str]) -> str:
    lines = [
        "# Generated by scripts/sync-guardrails-secret-patterns.py — do not edit manually.",
        f"# Source: gitleaks {metadata['gitleaks_version']} ({metadata['vendor_file']})",
        f"# Synced: {metadata['synced_at']}",
        f"# Pattern count: {metadata['pattern_count']}",
        "",
        "metadata:",
        f"  gitleaks_version: {metadata['gitleaks_version']}",
        f"  vendor_file: {metadata['vendor_file']}",
        f"  synced_at: {metadata['synced_at']}",
        f"  pattern_count: {metadata['pattern_count']}",
        "patterns:",
    ]
    for pattern in patterns:
        escaped = pattern.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  - "{escaped}"')
    return "\n".join(lines) + "\n"


def extract_gitleaks_regexes(toml_path: Path) -> tuple[list[str], list[tuple[str, str]]]:
    """Return (valid_patterns, skipped) where skipped is (pattern, reason)."""
    raw = tomllib.loads(toml_path.read_text(encoding="utf-8"))
    candidates: list[str] = []
    for rule in raw.get("rules", []):
        regex = rule.get("regex")
        if isinstance(regex, str) and regex.strip():
            candidates.append(regex.strip())
        regexes = rule.get("regexes")
        if isinstance(regexes, list):
            for item in regexes:
                if isinstance(item, str) and item.strip():
                    candidates.append(item.strip())

    valid: list[str] = []
    skipped: list[tuple[str, str]] = []
    seen: set[str] = set()
    for pattern in candidates:
        if pattern in seen:
            continue
        seen.add(pattern)
        try:
            re.compile(pattern)
            valid.append(pattern)
        except re.error as exc:
            skipped.append((pattern, str(exc)))
    return valid, skipped


def build_pattern_list() -> tuple[list[str], list[tuple[str, str]]]:
    overrides = _load_yaml_simple(OVERRIDES_PATH)
    patterns, skipped = extract_gitleaks_regexes(GITLEAKS_VENDOR)

    remove_set = set(overrides.get("remove", []))
    patterns = [p for p in patterns if p not in remove_set]

    for extra in overrides.get("add", []):
        try:
            re.compile(extra)
        except re.error as exc:
            skipped.append((extra, f"override add: {exc}"))
            continue
        if extra not in patterns:
            patterns.append(extra)

    return patterns, skipped


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync guardrails secret patterns from gitleaks")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if secret-patterns.yaml is stale",
    )
    args = parser.parse_args()

    if not GITLEAKS_VENDOR.is_file():
        print(f"ERROR: missing vendor file {GITLEAKS_VENDOR}", file=sys.stderr)
        return 1
    if not OVERRIDES_PATH.is_file():
        print(f"ERROR: missing overrides file {OVERRIDES_PATH}", file=sys.stderr)
        return 1

    patterns, skipped = build_pattern_list()
    if not patterns:
        print("ERROR: no valid patterns after sync", file=sys.stderr)
        return 1

    metadata = {
        "gitleaks_version": GITLEAKS_VERSION,
        "vendor_file": "scripts/vendor/gitleaks-v8.24.2.toml",
        "synced_at": date.today().isoformat(),
        "pattern_count": len(patterns),
    }

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"ERROR: {OUTPUT_PATH} does not exist; run make sync-guardrails-patterns", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        synced_match = re.search(r"^  synced_at: (.+)$", current, re.MULTILINE)
        if synced_match:
            metadata["synced_at"] = synced_match.group(1).strip()
        new_text = _format_yaml(metadata, patterns)
        if current != new_text:
            print(
                "ERROR: secret-patterns.yaml is stale; run make sync-guardrails-patterns",
                file=sys.stderr,
            )
            return 1
        print(f"OK: secret-patterns.yaml is up to date ({len(patterns)} patterns)")
        return 0

    new_text = _format_yaml(metadata, patterns)

    if skipped:
        print(f"Skipped {len(skipped)} patterns (not valid Python regex):")
        for pattern, reason in skipped[:10]:
            preview = pattern[:80] + ("..." if len(pattern) > 80 else "")
            print(f"  - {preview!r}: {reason}")
        if len(skipped) > 10:
            print(f"  ... and {len(skipped) - 10} more")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(new_text, encoding="utf-8")
    print(f"Wrote {len(patterns)} patterns to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
