# Namespace for the AI platform
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: private-code-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- if .Values.devspaces.enabled }}
{{- range .Values.devspaces.instances }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    che.eclipse.org/username: {{ .user }}
{{- end }}
{{- end }}
