{{- if and .Values.clusterConfig.enabled .Values.auth.htpasswd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pca-htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  htpasswd: |
    {{- range .Values.devspaces.instances }}
    {{- if .password }}
    {{ htpasswd .user .password }}
    {{- end }}
    {{- end }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  identityProviders:
    - name: {{ .Values.auth.htpasswd.providerName }}
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: pca-htpass-secret
{{- end }}
